# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Admin2(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, admin2: List[str]=None):  # noqa: E501
        """Admin2 - a model defined in OpenAPI

        :param admin2: The admin2 of this Admin2.  # noqa: E501
        :type admin2: List[str]
        """
        self.openapi_types = {
            'admin2': List[str]
        }

        self.attribute_map = {
            'admin2': 'admin2'
        }

        self._admin2 = admin2

    @classmethod
    def from_dict(cls, dikt) -> 'Admin2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The admin2 of this Admin2.  # noqa: E501
        :rtype: Admin2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def admin2(self) -> List[str]:
        """Gets the admin2 of this Admin2.


        :return: The admin2 of this Admin2.
        :rtype: List[str]
        """
        return self._admin2

    @admin2.setter
    def admin2(self, admin2: List[str]):
        """Sets the admin2 of this Admin2.


        :param admin2: The admin2 of this Admin2.
        :type admin2: List[str]
        """

        self._admin2 = admin2
