# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Admin1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, admin1: List[str]=None):  # noqa: E501
        """Admin1 - a model defined in OpenAPI

        :param admin1: The admin1 of this Admin1.  # noqa: E501
        :type admin1: List[str]
        """
        self.openapi_types = {
            'admin1': List[str]
        }

        self.attribute_map = {
            'admin1': 'admin1'
        }

        self._admin1 = admin1

    @classmethod
    def from_dict(cls, dikt) -> 'Admin1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The admin1 of this Admin1.  # noqa: E501
        :rtype: Admin1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def admin1(self) -> List[str]:
        """Gets the admin1 of this Admin1.


        :return: The admin1 of this Admin1.
        :rtype: List[str]
        """
        return self._admin1

    @admin1.setter
    def admin1(self, admin1: List[str]):
        """Sets the admin1 of this Admin1.


        :param admin1: The admin1 of this Admin1.
        :type admin1: List[str]
        """

        self._admin1 = admin1
