# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Admin3(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, admin3: List[str]=None):  # noqa: E501
        """Admin3 - a model defined in OpenAPI

        :param admin3: The admin3 of this Admin3.  # noqa: E501
        :type admin3: List[str]
        """
        self.openapi_types = {
            'admin3': List[str]
        }

        self.attribute_map = {
            'admin3': 'admin3'
        }

        self._admin3 = admin3

    @classmethod
    def from_dict(cls, dikt) -> 'Admin3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The admin3 of this Admin3.  # noqa: E501
        :rtype: Admin3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def admin3(self) -> List[str]:
        """Gets the admin3 of this Admin3.


        :return: The admin3 of this Admin3.
        :rtype: List[str]
        """
        return self._admin3

    @admin3.setter
    def admin3(self, admin3: List[str]):
        """Sets the admin3 of this Admin3.


        :param admin3: The admin3 of this Admin3.
        :type admin3: List[str]
        """

        self._admin3 = admin3
