# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Geo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, area_name: List[str]=None):  # noqa: E501
        """Geo - a model defined in OpenAPI

        :param area_name: The area_name of this Geo.  # noqa: E501
        :type area_name: List[str]
        """
        self.openapi_types = {
            'area_name': List[str]
        }

        self.attribute_map = {
            'area_name': 'area_name'
        }

        self._area_name = area_name

    @classmethod
    def from_dict(cls, dikt) -> 'Geo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The geo of this Geo.  # noqa: E501
        :rtype: Geo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def area_name(self) -> List[str]:
        """Gets the area_name of this Geo.


        :return: The area_name of this Geo.
        :rtype: List[str]
        """
        return self._area_name

    @area_name.setter
    def area_name(self, area_name: List[str]):
        """Sets the area_name of this Geo.


        :param area_name: The area_name of this Geo.
        :type area_name: List[str]
        """
        if area_name is None:
            raise ValueError("Invalid value for `area_name`, must not be `None`")  # noqa: E501

        self._area_name = area_name
