# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.keyword_search_keywords import KeywordSearchKeywords  # noqa: F401,E501
from openapi_server import util


class KeywordSearch(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, keywords: KeywordSearchKeywords=None):  # noqa: E501
        """KeywordSearch - a model defined in OpenAPI

        :param keywords: The keywords of this KeywordSearch.  # noqa: E501
        :type keywords: KeywordSearchKeywords
        """
        self.openapi_types = {
            'keywords': KeywordSearchKeywords
        }

        self.attribute_map = {
            'keywords': 'keywords'
        }

        self._keywords = keywords

    @classmethod
    def from_dict(cls, dikt) -> 'KeywordSearch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The keyword_search of this KeywordSearch.  # noqa: E501
        :rtype: KeywordSearch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def keywords(self) -> KeywordSearchKeywords:
        """Gets the keywords of this KeywordSearch.


        :return: The keywords of this KeywordSearch.
        :rtype: KeywordSearchKeywords
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords: KeywordSearchKeywords):
        """Sets the keywords of this KeywordSearch.


        :param keywords: The keywords of this KeywordSearch.
        :type keywords: KeywordSearchKeywords
        """

        self._keywords = keywords
