# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TemporalSearchTime(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start: str=None, end: str=None):  # noqa: E501
        """TemporalSearchTime - a model defined in OpenAPI

        :param start: The start of this TemporalSearchTime.  # noqa: E501
        :type start: str
        :param end: The end of this TemporalSearchTime.  # noqa: E501
        :type end: str
        """
        self.openapi_types = {
            'start': str,
            'end': str
        }

        self.attribute_map = {
            'start': 'start',
            'end': 'end'
        }

        self._start = start
        self._end = end

    @classmethod
    def from_dict(cls, dikt) -> 'TemporalSearchTime':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The temporal_search_time of this TemporalSearchTime.  # noqa: E501
        :rtype: TemporalSearchTime
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self) -> str:
        """Gets the start of this TemporalSearchTime.

        Dates-of-interest are more recent than this date  # noqa: E501

        :return: The start of this TemporalSearchTime.
        :rtype: str
        """
        return self._start

    @start.setter
    def start(self, start: str):
        """Sets the start of this TemporalSearchTime.

        Dates-of-interest are more recent than this date  # noqa: E501

        :param start: The start of this TemporalSearchTime.
        :type start: str
        """

        self._start = start

    @property
    def end(self) -> str:
        """Gets the end of this TemporalSearchTime.

        Dates-of-interest are older than this date  # noqa: E501

        :return: The end of this TemporalSearchTime.
        :rtype: str
        """
        return self._end

    @end.setter
    def end(self, end: str):
        """Sets the end of this TemporalSearchTime.

        Dates-of-interest are older than this date  # noqa: E501

        :param end: The end of this TemporalSearchTime.
        :type end: str
        """

        self._end = end
