# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.temporal_search_time import TemporalSearchTime  # noqa: F401,E501
from openapi_server import util


class TemporalSearch(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time: TemporalSearchTime=None):  # noqa: E501
        """TemporalSearch - a model defined in OpenAPI

        :param time: The time of this TemporalSearch.  # noqa: E501
        :type time: TemporalSearchTime
        """
        self.openapi_types = {
            'time': TemporalSearchTime
        }

        self.attribute_map = {
            'time': 'time'
        }

        self._time = time

    @classmethod
    def from_dict(cls, dikt) -> 'TemporalSearch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The temporal_search of this TemporalSearch.  # noqa: E501
        :rtype: TemporalSearch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time(self) -> TemporalSearchTime:
        """Gets the time of this TemporalSearch.


        :return: The time of this TemporalSearch.
        :rtype: TemporalSearchTime
        """
        return self._time

    @time.setter
    def time(self, time: TemporalSearchTime):
        """Sets the time of this TemporalSearch.


        :param time: The time of this TemporalSearch.
        :type time: TemporalSearchTime
        """

        self._time = time
