# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.id import Id  # noqa: F401,E501
from openapi_server.models.ids import Ids  # noqa: F401,E501
from openapi_server import util


class TimeseriesAll(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: Id=None):  # noqa: E501
        """TimeseriesAll - a model defined in OpenAPI

        :param id: The id of this TimeseriesAll.  # noqa: E501
        :type id: Id
        """
        self.openapi_types = {
            'id': Id
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'TimeseriesAll':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The timeseries_all of this TimeseriesAll.  # noqa: E501
        :rtype: TimeseriesAll
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> Id:
        """Gets the id of this TimeseriesAll.


        :return: The id of this TimeseriesAll.
        :rtype: Id
        """
        return self._id

    @id.setter
    def id(self, id: Id):
        """Sets the id of this TimeseriesAll.


        :param id: The id of this TimeseriesAll.
        :type id: Id
        """

        self._id = id
